title: Joseph D. Paquette
author: jdpaquette
email: josephdpaquette@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is going to be my blog site for trying out the GitHub pages. 
  I am in the process of "mastering" GitHub and want to implement this into my coding classes.
  I wish to impress upon my sudents the need for version control and contributing to the 
  open source community. 

# social links
twitter_username: @josephdpaquette
github_username:  @jdpaquette

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
